function updateMap(origin, destination) {
    // Clear existing markers and line
    if (originMarker) originMarker.remove();
    if (destinationMarker) destinationMarker.remove();
    if (map.getSource('route')) map.removeLayer('route').removeSource('route');

    // Add markers for the airports
    originMarker = new mapboxgl.Marker({ color: 'green' })
        .setLngLat([origin.Longitude, origin.Latitude])
        .addTo(map);
    destinationMarker = new mapboxgl.Marker({ color: 'blue' })
        .setLngLat([destination.Longitude, destination.Latitude])
        .addTo(map);

    // Generate the great circle route using Turf.js
    const route = turf.greatCircle(
        [origin.Longitude, origin.Latitude],
        [destination.Longitude, destination.Latitude]
    );

    // Add the route source to the map
    map.addSource('route', {
        type: 'geojson',
        data: route // Pass the GeoJSON generated by Turf.js
    });

    map.addLayer({
        id: 'route',
        type: 'line',
        source: 'route',
        layout: {},
        paint: {
            'line-color': '#ff0000',
            'line-width': 4,
            'line-opacity': 0.8
        }
    });

    // Fit the map bounds to the route
    const bounds = new mapboxgl.LngLatBounds();
    route.geometry.coordinates.forEach(coord => bounds.extend(coord));
    map.fitBounds(bounds, { padding: 20 });
}
